// Array with 30 motivational / determination quotes (anime, movies, books, misc)
module.exports = [
  "Não importa o quão devagar você vá, desde que você não pare. — Confúcio",
  "Não lute porque odeia o que está à sua frente. Lute para proteger o que você ama. — Naruto",
  "É a escolha de cada um que define quem ele é. — One Piece",
  "Não posso voltar, mas posso seguir em frente. — Hayao Miyazaki",
  "O sucesso é ir de fracasso em fracasso sem perder o entusiasmo. — Winston Churchill",
  "A maior glória em viver não está em nunca cair, mas em nos levantar cada vez que caímos. — Nelson Mandela",
  "A vida encontra um caminho. — Jurassic Park",
  "O medo é só um obstáculo; a coragem é uma decisão. — Autor desconhecido",
  "A determinação é o que transforma sonhos em realidade. — Autor desconhecido",
  "Você não pode mudar o passado, mas pode decidir seu amanhã. — Autor desconhecido",
  "Mesmo que eu morra, não perco meu orgulho. — Anime / citação de determinação",
  "O único limite é aquele que você impõe a si mesmo. — Autor desconhecido",
  "Às vezes, as coisas pequenas ocupam mais espaço no seu coração. — Winnie the Pooh",
  "Não é a força, mas a perseverança que realiza grandes coisas. — Samuel Johnson",
  "O fracasso é apenas a oportunidade de recomeçar com mais inteligência. — Henry Ford",
  "Se você não quer que ninguém saiba, não faça. Mas faça algo de que possa se orgulhar. — Autor desconhecido",
  "A coragem não é ausência do medo, é a decisão de que algo é mais importante que o medo. — Ambrose Redmoon",
  "A dor é temporária. O orgulho é para sempre. — Autor desconhecido",
  "Não espere por oportunidades, crie-as. — George Bernard Shaw",
  "O impossível é apenas uma opinião. — Paulo Coelho",
  "Se você se concentrar no que deixou para trás, nunca verá o que está à frente. — Autor desconhecido",
  "Faça hoje o que outros não fazem, e amanhã viverá como outros não vivem. — Autor desconhecido",
  "Mesmo a noite mais escura terminará com o amanhecer. — Victor Hugo",
  "A disciplina é a ponte entre metas e conquistas. — Jim Rohn",
  "Quando tudo estiver contra você, lembre-se: o avião decola contra o vento. — Henry Ford",
  "A única maneira de vencer é continuar tentando. — Rocky Balboa",
  "Não importa quantas vezes você falha — levante-se uma vez a mais. — Autor desconhecido",
  "Você é mais forte do que pensa. — Autor desconhecido",
  "Transforme suas feridas em sabedoria. — Oprah Winfrey"
];
